module.exports = {
  SET_COMMUNITY_CHAT: "SET_COMMUNITY_CHAT",
  GET_COMMUNITY_CHAT: "GET_COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  NEW_MESSAGE: "NEW_MESSAGE",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING"
};
