matrix:
  include:
    - language: python
      python: 3.6.7
      before_install:
        - mkdir build && touch build/index.html
        - cd webserver
      install:
        - pip install -r requirements.txt
      script:
        - pytest

notifications:
  email:
    - pierre.thevenet@protonmail.com
    - philippe.weier@epfl.ch
