# development docker-compose

version: '3'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app
    networks:
      - backend
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  webserver:
    depends_on:
      - database
    build: ./webserver
    restart: always
    environment:
      - WEBSERVER_PORT=3000
    volumes:
      - ./build:/app/build
    ports:
      - 3000:3000
    networks:
      - backend
      - external

networks:
  backend:
    driver: bridge
  external:
    driver: bridge
