version: '3'

services:
  website:
    build: ./webserver
    environment:
      - WEBSERVER_PORT=3000
    volumes:
      - ./build:/app/build
    ports:
      - 3000:3000


  database:
    build: ./database
    environment:
      - DATABASE_PORT=5000
    volumes:
      - ./database:/app
    ports:
      - 5000:5000
      